# Generated by Django 5.0.6 on 2024-09-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livro',
            new_name='Livros',
        ),
    ]
